source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftJavascriptBridge_Example', :exclusive => true do
  pod "SwiftJavascriptBridge", :path => "../"
end

target 'SwiftJavascriptBridge_Tests', :exclusive => true do
  pod "SwiftJavascriptBridge", :path => "../"
end
